-- begin MAPSDEMO_ORDER
alter table MAPSDEMO_ORDER add constraint FK_MAPSDEMO_ORDER_ON_SALESPERSON foreign key (SALESPERSON_ID) references MAPSDEMO_SALESPERSON(ID)^
create index IDX_MAPSDEMO_ORDER_ON_SALESPERSON on MAPSDEMO_ORDER (SALESPERSON_ID)^
-- end MAPSDEMO_ORDER
-- begin MAPSDEMO_SALESPERSON
alter table MAPSDEMO_SALESPERSON add constraint FK_MAPSDEMO_SALESPERSON_ON_TERRITORY foreign key (TERRITORY_ID) references MAPSDEMO_TERRITORY(ID)^
create index IDX_MAPSDEMO_SALESPERSON_ON_TERRITORY on MAPSDEMO_SALESPERSON (TERRITORY_ID)^
-- end MAPSDEMO_SALESPERSON
